name: CI Pipeline

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  ######################## 1. Test ########################
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      - name: Run tests
        run: mvn clean test

  ######################## 2. Release ########################
  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      - name: Bump patch version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH + 1))
          VERSION="$MAJOR.$MINOR.$PATCH"

          mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add pom.xml
          git commit -m "release: bump version to $VERSION"
          git push origin master

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build & push Docker image
        run: |
          docker build -t simple-java-maven-app:${{ env.VERSION }} .

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker tag simple-java-maven-app:${{ env.VERSION }} $REGISTRY/${{ github.repository }}:${{ env.VERSION }}
          docker push $REGISTRY/${{ github.repository }}:${{ env.VERSION }}
